# Generated by Django 5.1.4 on 2025-01-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TugasAkhir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_ta', models.CharField(max_length=10)),
                ('nim', models.CharField(max_length=15)),
                ('nama', models.CharField(max_length=100)),
                ('judul', models.TextField()),
            ],
        ),
    ]
